import k1 from '../Assets/examples/k1.jpg';
import k2 from '../Assets/examples/k2.jpg';
import k3 from '../Assets/examples/k3.jpg';
import k4 from '../Assets/examples/k4.jpeg';
import cc from '../Assets/examples/cc.jpg';
import w22 from '../Assets/examples/w22.jpg';
export const products = [
  {
    id: 1,
    code: "",
    name: "مطبخ أرجان",
    matrial: "خشمونيوم",
    dis: " قطع مطبخ مصنوع من الوميتال مع فيبر مستورد نمرة واحد اكسسوار لوكس + زجاج مكربن",
    sector: "ps",
    size: "4-m^2",
    pieces: 2,
    colors: [],
    Accessories: "loux",
    imgsURL: [k1, cc, w22],
    price: 9000,
    estimatTime: 7,
    category: "مطابخ",
    likes: 10,
    fav: 5,
    clicked: 100,
    ordered: 0,
    canceled: 0,
    rated:0,
    timeAdded:"",
    avaliable: true
  
  },    
  {
    id: 2,
    code: "",
    name: "مطبخ أرجان",
    matrial: "خشمونيوم",
    dis: " قطع مطبخ مصنوع من الوميتال مع فيبر مستورد نمرة واحد اكسسوار لوكس + زجاج مكربن",
    sector: "ps",
    size: "4-m^2",
    pieces: 2,
    colors: [],
    Accessories: "loux",
    imgsURL: [k1, k1, k1],
    price: 9000,
    estimatTime: 7,
    category: "مطابخ",
    likes: 10,
    fav: 5,
    clicked: 100,
    ordered: 0,
    canceled: 0,
    rated:0,
    timeAdded:"",
    avaliable: true
  
  },    
  {
    id: 3,
    code: "",
    name: "مطبخ أرجان",
    matrial: "خشمونيوم",
    dis: " قطع مطبخ مصنوع من الوميتال مع فيبر مستورد نمرة واحد اكسسوار لوكس + زجاج مكربن",
    sector: "ps",
    size: "4-m^2",
    pieces: 2,
    colors: [],
    Accessories: "loux",
    imgsURL: [k1, k1, k1],
    price: 9000,
    estimatTime: 7,
    category: "مطابخ",
    likes: 10,
    fav: 5,
    clicked: 100,
    ordered: 0,
    canceled: 0,
    rated:0,
    timeAdded:"",
    avaliable: true
  
  },    
  {
    id: 4,
    code: "",
    name: "مطبخ أرجان",
    matrial: "خشمونيوم",
    dis: " قطع مطبخ مصنوع من الوميتال مع فيبر مستورد نمرة واحد اكسسوار لوكس + زجاج مكربن",
    sector: "ps",
    size: "4-m^2",
    pieces: 2,
    colors: [],
    Accessories: "loux",
    imgsURL: [k1, k1, k1],
    price: 9000,
    estimatTime: 7,
    category: "مطابخ",
    likes: 10,
    fav: 5,
    clicked: 100,
    ordered: 0,
    canceled: 0,
    rated:0,
    timeAdded:"",
    avaliable: true
  
  },    
  {
    id: 5,
    code: "",
    name: "مطبخ أرجان",
    matrial: "خشمونيوم",
    dis: " قطع مطبخ مصنوع من الوميتال مع فيبر مستورد نمرة واحد اكسسوار لوكس + زجاج مكربن",
    sector: "ps",
    size: "4-m^2",
    pieces: 2,
    colors: [],
    Accessories: "loux",
    imgsURL: [k1, k1, k1],
    price: 9000,
    estimatTime: 7,
    category: "مطابخ",
    likes: 10,
    fav: 5,
    clicked: 100,
    ordered: 0,
    canceled: 0,
    rated:0,
    timeAdded:"",
    avaliable: true
  
  },    
  {
    id: 6,
    code: "",
    name: "مطبخ أرجان",
    matrial: "خشمونيوم",
    dis: " قطع مطبخ مصنوع من الوميتال مع فيبر مستورد نمرة واحد اكسسوار لوكس + زجاج مكربن",
    sector: "ps",
    size: "4-m^2",
    pieces: 2,
    colors: [],
    Accessories: "loux",
    imgsURL: [k1, k1, k1],
    price: 9000,
    estimatTime: 7,
    category: "مطابخ",
    likes: 10,
    fav: 5,
    clicked: 100,
    ordered: 0,
    canceled: 0,
    rated:0,
    timeAdded:"",
    avaliable: true
  
  },    
  {
    id: 7,
    code: "",
    name: "مطبخ أرجان",
    matrial: "خشمونيوم",
    dis: " قطع مطبخ مصنوع من الوميتال مع فيبر مستورد نمرة واحد اكسسوار لوكس + زجاج مكربن",
    sector: "ps",
    size: "4-m^2",
    pieces: 2,
    colors: [],
    Accessories: "loux",
    imgsURL: [k2, k2, k2],
    price: 9000,
    estimatTime: 7,
    category: "حمام",
    likes: 10,
    fav: 5,
    clicked: 100,
    ordered: 0,
    canceled: 0,
    rated:0,
    timeAdded:"",
    avaliable: true
  
  },    
  {
    id: 8,
    code: "",
    name: "مطبخ أرجان",
    matrial: "خشمونيوم",
    dis: " قطع مطبخ مصنوع من الوميتال مع فيبر مستورد نمرة واحد اكسسوار لوكس + زجاج مكربن",
    sector: "ps",
    size: "4-m^2",
    pieces: 2,
    colors: [],
    Accessories: "loux",
    imgsURL: [cc, cc, cc],
    price: 9000,
    estimatTime: 7,
    category: "شبابيك",
    likes: 10,
    fav: 5,
    clicked: 100,
    ordered: 0,
    canceled: 0,
    rated:0,
    timeAdded:"",
    avaliable: true
  
  },    
  {
    id: 9,
    code: "",
    name: "مطبخ أرجان",
    matrial: "خشمونيوم",
    dis: " قطع مطبخ مصنوع من الوميتال مع فيبر مستورد نمرة واحد اكسسوار لوكس + زجاج مكربن",
    sector: "ps",
    size: "4-m^2",
    pieces: 2,
    colors: ["اسمر", "أحمر","أصفر", "بصلي"],
    Accessories: "loux",
    imgsURL: [k1, k1, k1],
    price: 9000,
    estimatTime: 7,
    category: "ابواب",
    likes: 10,
    fav: 5,
    clicked: 100,
    ordered: 0,
    canceled: 0,
    rated:0,
    timeAdded:"",
    avaliable: true
  },    
  {
    id: 10,
    code: "",
    name: "مطبخ أرجان",
    matrial: "خشمونيوم",
    dis: " قطع مطبخ مصنوع من الوميتال مع فيبر مستورد نمرة واحد اكسسوار لوكس + زجاج مكربن",
    sector: "ps",
    size: "4-m^2",
    pieces: 2,
    colors: [],
    Accessories: "loux",
    imgsURL: [w22, w22, w22],
    price: 9000,
    estimatTime: 7,
    category: "شبابيك",
    likes: 10,
    fav: 5,
    clicked: 100,
    ordered: 0,
    canceled: 0,
    rated:0,
    timeAdded:"",
    avaliable: true
  
  },      
]

export const categories = ["الكل", "ابواب", "شبابيك", "حمام", "مطابخ"]